### ISSUE TITLE
希望添加进入视频页面自动播放的开关

### ISSUE THREAD

**Issue by MisakaSakura** [jiangdashao/iwara4a#2]
有些时候点进去一个视频并不一定要播放，可能只是想看up的其他视频，但是自动播放会消耗巨大流量（不得不说开发者开发的app在视频加载方面比浏览器快多了），所以需要一个默认关闭自动播放的功能或者开关。另外好久没看到这么标准的md app了，谷歌自己都改的妈都不认得了，如果图标能改好点就更好了

**Comment by jiangdashao** [comment]
好的，会加上这个设定的

**Comment by jiangdashao** [comment]
图标哪里不好呢，我用的谷歌官方的图标，还是你指的是app logo?

**Comment by MisakaSakura** [comment]
> 图标哪里不好呢，我用的谷歌官方的图标，还是你指的是app logo?

是的，你这个蓝底黑字看着显得太... ...廉价了，其实应用本身应用名就足以识别了，logo不如换成二次元图片（只是提个建议，还看您自己决定，但是现在logo观感确实不行）

**Comment by jiangdashao** [comment]
直男不懂设计，搞logo确实麻烦

**Comment by MisakaSakura** [comment]
> 直男不懂设计，搞logo确实麻烦

其实可以借鉴一些动画的客户端logo还有图标包的logo，最简单的就是用张自己喜欢的二次元头像加上名称当logo，当然不用字也是很常见的
