### ISSUE TITLE
2个问题

### ISSUE THREAD

**Issue by Alienxzy** [jiangdashao/iwara4a#8]
1.浏览组图时不能左右滑动切换图片，只能通过顶部TAB切换，比较麻烦；
2.当系统已经设置旋转方向锁定时，手机稍微倾斜，应用仍然可以直接进入全屏状态，观看竖屏视频时很不方便

**Comment by jiangdashao** [comment]
1. 因为这和图片的拖动手势冲突，所以我禁用了
2. 好的，下个版本修

**Comment by jiangdashao** [comment]
已发布
